---
title: "Quality_Checks"
author: "LuciaSegovia"
date: "8/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Within the quality checks we will find c of interest and sum of proximate (SOP) calculated as the sum of water, protein, fat, available carbohydrates, dietary fibre (or total carbohydrates), alcohol (if applicable) and ash. And, percentage of sum of proximate above or below recommended thresholds (FAO/INFOODS, 2013).


##Quality Checks

 1) Sum of Proximates:
 
 We are going to check the average and standard desviation of the sum of proximates. Then, we are going to explore the percentage of items that fall within prefered and acceptable limits for the sum of proximates. We will use as reference the values given by the FAO/INFOODS guidelines (REF). 
 
 
After checking the average values and sd, we have decided to exclude two FCT: NGAFCT and ETHFCT. Then, after checking the percentage of *fooditems* that fall out of the preferred and acceptable limits, we are excluiding GMBFCT and UGAFCT as well. 

For some FCT such as WAFCT, we need to re-calculate SOP to be compared witht he orinal data in the FCT.

NOTE: The problem with converting to numeric is that number between [] are removed (as NA). It is also creating a issue with the calculation of SOP

 2) ASH 
 
This quality check is important particularly for our project. This step will allow us to identify extremely high minerals values (ASH_cal > ASH). 

 3) MINIMUM AND MAXIMUM VALUES 
 
We had identified extreme values in MAFOODS. After looking at those values references, we identified that a great proportion (n=17) of those values were coming from the same ref. (ref.10). The ref.10 is Joy, et. al. 2015, from this point onwards that paper and the data linked to that will be called EJ1. We accessed the data of that EJ1 and we identified that there was an issue with the conversion of the values from the original source to the MAFOODS. In order to solve that issue, we have recalculated the values for those minerals. More information regarding that process can be found in 'fct_cleaning'. 

CA - acc. to USDA data the highest value is for firm tofu (683mg/100g). Most of the extreme value were in animal category followed by vegetables. In total, 22 items were higher than 700mg/100g. 

CU

FE - acc. to USDA data the highest value is for fortified cereals with 67.7mg/100g. We found a cod product (branded product) with 177mg/100g. 
 
 4) VARIABILITY OF THE SAMPLES (only for analytic data)
 
After having re
 
 
